server:
    port: 8888
spring:
#mysql数据库配置
    datasource:
       url: jdbc:mysql://127.0.0.1:3306/sgd?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
       username: root
       password: 1234
       driver-class-name: com.mysql.jdbc.Driver
    application:
       name: SchoolGoodsDisplace
    cloud:
       client:
          ipAddress: 127.0.0.1
#redis
    redis:
       host: 127.0.0.1
       port: 6379
       database: 0
       jedis:
          pool:
             max-active: 50
             max-wait: 3000
             max-idle: 20
             min-idle: 2
       timeout: 5000
#mybatis
mybatis:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.taokoo.dao
   


           
      
   
     