server:
    port: 8088
spring:
#mysql数据库配置
    datasource:
       url: jdbc:mysql://127.0.0.1:3306/bpm_flowable?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
       username: root
       password: 1234
       driver-class-name: com.mysql.jdbc.Driver
    application:
       name: Service2
    cloud:
       client:
          ipAddress: 127.0.0.1
          
     